{ lib, pkgs, ... }:

let
  # Pi is not currently packaged by nixpkgs. Build the published package with
  # its lockfile and keep the application version pinned independently of the
  # rest of the Nix channel.
  piPackage = pkgs.buildNpmPackage {
    pname = "pi-coding-agent";
    version = "0.99.1";

    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/@earendil-works/pi-coding-agent/-/pi-coding-agent-0.99.1.tgz";
      hash = "sha256-ZoZZKtrqGQkshclPXUAyPb89sUHpDrPt6enocwKr3R0=";
    };

    # scripts/update-pi persists a lockfile when upstream ships none and repairs
    # missing sibling integrity metadata in older published lockfiles. The
    # generated block supplies the exact lockfile used to calculate npmDepsHash.
    postPatch = ''
      JQ=${pkgs.jq}/bin/jq ${pkgs.bash}/bin/bash ${../../scripts/patch-pi-package.sh} package.json
      # BEGIN npm lockfile generated by scripts/update-pi
      sed -i '/chord-0.99.1.tgz/ a\
          "integrity": "sha512-4xyn0IBzJ+Xu/iOGi2hjXJGAR61QEhEWZsIqTDqr+GmItdquYwBO5jYFnqGiBaTqlY12/EpM7QHoEKSHbyvOug==",' npm-shrinkwrap.json
      sed -i '/pi-agent-core-0.99.1.tgz/ a\
          "integrity": "sha512-zywvWnj5FujeuFI/x/CJHwwxhcLIQgjqseTA+bQgX4O8gJTcgjRd/I8SZnQDqJvxC9QcV12ujiGLviv6EgwcCg==",' npm-shrinkwrap.json
      sed -i '/pi-ai-0.99.1.tgz/ a\
          "integrity": "sha512-4nV9JKc94iPX8bwdGPc2nTuVPKIPsffhnp3WoN9NYCNqbtoOF8LhYcIs/+Sn/alroqJK/5QRu6/Z6Ck+n0hyBA==",' npm-shrinkwrap.json
      sed -i '/pi-codemode-0.99.1.tgz/ a\
          "integrity": "sha512-oh8TMsBI3SWTN3xTQtX8u5n+BKhnVXcFagroWumfn6/WWfBnDYL/LmeQtjLb83WRTb9rcu+ZdK8rFa4vggvCJg==",' npm-shrinkwrap.json
      sed -i '/pi-mcp-0.99.1.tgz/ a\
          "integrity": "sha512-YCFGPkmDzLwQuIzwfbP6Vuk/g/ukKpZhwTpbcfzomuI1Fkiu6hHRkOGwAqsO3G8cTkZWkM8vmOkFJjStQNC4qA==",' npm-shrinkwrap.json
      sed -i '/pi-telemetry-0.99.1.tgz/ a\
          "integrity": "sha512-9PBPjGk+TXRtuMianpqBbHBpYpyKusESF6rwdmgD0WTZSTUQXhcKEO0hAINRLuSwy4V7yPvXV+EVV0ONY7mbpQ==",' npm-shrinkwrap.json
      sed -i '/pi-tui-0.99.1.tgz/ a\
          "integrity": "sha512-gZp0Guat96Fr1AuC/xqVz5B2lulZakp/PxD1lXx3lSgBdjiqmwYhJbcQ0HRrGAfy0WtMGn9b05RJr5qJf7oIuw==",' npm-shrinkwrap.json
      # END npm lockfile generated by scripts/update-pi
    '';

    npmDepsFetcherVersion = 2;
    npmDepsHash = "sha256-q3oHOSNFfLqv7Ld8OPTrKcDaE52Rk0dMbKZ5MkMzBN8=";
    npmInstallFlags = [ "--omit=dev" ];
    npmFlags = [ "--omit=dev" ];
    dontNpmBuild = true;

    installPhase = ''
      runHook preInstall
      mkdir -p $out/lib/node_modules/@earendil-works/pi-coding-agent
      cp -r . $out/lib/node_modules/@earendil-works/pi-coding-agent/
      mkdir -p $out/bin
      cli=$(${pkgs.jq}/bin/jq -er '.bin.pi' package.json)
      test -f "$out/lib/node_modules/@earendil-works/pi-coding-agent/$cli"
      ln -s "$out/lib/node_modules/@earendil-works/pi-coding-agent/$cli" $out/bin/pi
      runHook postInstall
    '';
  };

  piSettings = ../../config/pi/agent/settings.json;
  piStaticRoot = ../../config/pi/agent;
  # Never link an entire Pi directory: Pi keeps sessions, OAuth, npm state, and
  # locally installed extensions below the same writable parents. Each static
  # reference file is linked independently instead.
  piStaticFiles = builtins.filter (source: toString source != toString piSettings)
    (lib.filesystem.listFilesRecursive piStaticRoot);
  piStaticHomeFiles = builtins.listToAttrs (map (source: {
    name = ".pi/agent/${lib.removePrefix "${toString piStaticRoot}/" (toString source)}";
    value = {
      inherit source;
      force = true;
      executable = lib.hasPrefix "${toString piStaticRoot}/intercepted-commands/" (toString source);
    };
  }) piStaticFiles);
in
{
  home.packages = [ piPackage ];

  home.activation.piSettings = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    settings="$HOME/.pi/agent/settings.json"
    temporary="$settings.tmp.$$"
    mkdir -p "$(dirname "$settings")"

    # Preserve Pi's live changelog marker while refreshing managed settings
    # without leaving the runtime file as a read-only /nix/store symlink.
    last_changelog_version="0.0.0"
    if [ -f "$settings" ]; then
      last_changelog_version="$(${pkgs.jq}/bin/jq -r '.lastChangelogVersion // "0.0.0"' "$settings" 2>/dev/null || printf '%s' '0.0.0')"
    fi
    ${pkgs.jq}/bin/jq --arg version "$last_changelog_version" \
      '.lastChangelogVersion = $version' "${piSettings}" > "$temporary"
    chmod 0644 "$temporary"
    mv -f "$temporary" "$settings"
  '';

  home.file = piStaticHomeFiles // {
    ".pi/README.md" = { source = ../../config/pi/README.md; force = true; };
    ".pi/.gitignore" = { source = ../../config/pi/.gitignore; force = true; };
    ".pi/.nvmrc" = { source = ../../config/pi/.nvmrc; force = true; };
    ".local/bin/pi" = {
      source = ../../bin/pi;
      executable = true;
      force = true;
    };
    ".local/bin/proton-pass-pi-env" = {
      source = ../../bin/proton-pass-pi-env;
      executable = true;
      force = true;
    };
    ".pi/.claude/settings.local.json" = { source = ../../config/pi/.claude/settings.local.json; force = true; };
    ".claude/settings.local.json" = { source = ../../config/claude/settings.local.json; force = true; };
  };
}
