{ lib, pkgs, ... }:

let
  # Pi is not currently packaged by nixpkgs. Build the published package with
  # its lockfile and keep the application version pinned independently of the
  # rest of the Nix channel.
  piPackage = pkgs.buildNpmPackage {
    pname = "pi-coding-agent";
    version = "0.87.0";

    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/@earendil-works/pi-coding-agent/-/pi-coding-agent-0.87.0.tgz";
      hash = "sha256-mmczwOajHVkrU9xg30PdDCb6eTzPI4TtEj/BewRIhmo=";
    };

    # The published shrinkwrap omits integrity metadata for Pi's sibling
    # packages. Add the registry-published values before Nix prefetches npm
    # dependencies; the package is otherwise unchanged. The sibling set changes
    # between Pi releases, so scripts/update-pi regenerates the block below.
    postPatch = ''
      JQ=${pkgs.jq}/bin/jq ${pkgs.bash}/bin/bash ${../../scripts/patch-pi-package.sh} package.json
      # BEGIN sibling integrity fields generated by scripts/update-pi
      sed -i '/chord-0.87.0.tgz/ a\
          "integrity": "sha512-t8QOTf0GTHrsDSfcdtXuA9RCkh6mnR4l25N0SM/sgH7Ih25jH4tGXNbkGs9MWpV5xTu9MRPj4A7Zn1UEwQm9+g==",' npm-shrinkwrap.json
      sed -i '/pi-agent-core-0.87.0.tgz/ a\
          "integrity": "sha512-c5b2FMdJ7C++HBa6AyBmusdf96gdgRqpF7J+UCq2yVGB28UETJvJ190HkgDWUaLPnOQQPbanjKMAm/TgRmFE2w==",' npm-shrinkwrap.json
      sed -i '/pi-ai-0.87.0.tgz/ a\
          "integrity": "sha512-lbRm+EMY6Jx3l+HLpbqbm9Yrhkc5u7EffLk2id+zJQEoBuR5I+tijGiZU8zlnuuCclmQOgH0PVjL9PLbeqJ9MQ==",' npm-shrinkwrap.json
      sed -i '/pi-telemetry-0.87.0.tgz/ a\
          "integrity": "sha512-IEUMnV6mgHyOMfAxa4CKXoBKKfHM8KxNjbXWM4Bps/iLJcFMf8hQsEZ+95VnVTc7C0cU77Rmdxt773C35jb5AA==",' npm-shrinkwrap.json
      sed -i '/pi-tui-0.87.0.tgz/ a\
          "integrity": "sha512-7gTC0XOgQfVWg4yGxwHINBpCnGl9p4KEC7PXIc8gAwc/cyxSW4VuFQrp+r1YD3oM+rBkoepKwAt6w6+VJ7BCaw==",' npm-shrinkwrap.json
      # END sibling integrity fields generated by scripts/update-pi
    '';

    npmDepsFetcherVersion = 2;
    npmDepsHash = "sha256-0lkGJziWfYjwYdbw1TjSlVVjULAxpd8dWbFwTFaeKTY=";
    npmInstallFlags = [ "--omit=dev" ];
    npmFlags = [ "--omit=dev" ];
    dontNpmBuild = true;

    installPhase = ''
      runHook preInstall
      mkdir -p $out/lib/node_modules/@earendil-works/pi-coding-agent
      cp -r . $out/lib/node_modules/@earendil-works/pi-coding-agent/
      mkdir -p $out/bin
      ln -s $out/lib/node_modules/@earendil-works/pi-coding-agent/dist/cli.js $out/bin/pi
      runHook postInstall
    '';
  };

  piSettings = ../../config/pi/agent/settings.json;
  piStaticRoot = ../../config/pi/agent;
  # Never link an entire Pi directory: Pi keeps sessions, OAuth, npm state, and
  # locally installed extensions below the same writable parents. Each static
  # reference file is linked independently instead.
  piStaticFiles = builtins.filter (source: toString source != toString piSettings)
    (lib.filesystem.listFilesRecursive piStaticRoot);
  piStaticHomeFiles = builtins.listToAttrs (map (source: {
    name = ".pi/agent/${lib.removePrefix "${toString piStaticRoot}/" (toString source)}";
    value = {
      inherit source;
      force = true;
      executable = lib.hasPrefix "${toString piStaticRoot}/intercepted-commands/" (toString source);
    };
  }) piStaticFiles);
in
{
  home.packages = [ piPackage ];

  home.activation.piSettings = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    settings="$HOME/.pi/agent/settings.json"
    temporary="$settings.tmp.$$"
    mkdir -p "$(dirname "$settings")"

    # Preserve Pi's live changelog marker while refreshing managed settings
    # without leaving the runtime file as a read-only /nix/store symlink.
    last_changelog_version="0.0.0"
    if [ -f "$settings" ]; then
      last_changelog_version="$(${pkgs.jq}/bin/jq -r '.lastChangelogVersion // "0.0.0"' "$settings" 2>/dev/null || printf '%s' '0.0.0')"
    fi
    ${pkgs.jq}/bin/jq --arg version "$last_changelog_version" \
      '.lastChangelogVersion = $version' "${piSettings}" > "$temporary"
    chmod 0644 "$temporary"
    mv -f "$temporary" "$settings"
  '';

  home.file = piStaticHomeFiles // {
    ".pi/README.md" = { source = ../../config/pi/README.md; force = true; };
    ".pi/.gitignore" = { source = ../../config/pi/.gitignore; force = true; };
    ".pi/.nvmrc" = { source = ../../config/pi/.nvmrc; force = true; };
    ".local/bin/pi" = {
      source = ../../bin/pi;
      executable = true;
      force = true;
    };
    ".local/bin/proton-pass-pi-env" = {
      source = ../../bin/proton-pass-pi-env;
      executable = true;
      force = true;
    };
    ".pi/.claude/settings.local.json" = { source = ../../config/pi/.claude/settings.local.json; force = true; };
    ".claude/settings.local.json" = { source = ../../config/claude/settings.local.json; force = true; };
  };
}
