import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const messages = [
  // GREETINGS & RESPONSES
  "오랜만이에요 (oraenmanieyo) · long time no see · lama tidak bertemu",
  "잘 지냈어요 (jal jinaesseoyo) · have you been well · apa kabar",
  "수고했어요 (sugohaesseoyo) · good work / thanks for your effort · terima kasih atas usahanya",
  "조심히 가세요 (josimhi gaseyo) · get home safely · hati-hati di jalan",
  "맞아요 (majayo) · that's right · benar",
  "그렇죠 (geureochyo) · right? / isn't it · iya kan",
  "그러게요 (geureogeyo) · I know, right · iya ya",
  "글쎄요 (geulsseyo) · hmm, not sure · entahlah",
  "아무튼 (amuteun) · anyway · pokoknya",
  "그나저나 (geunajeona) · by the way · ngomong-ngomong",

  // EVERYDAY FEELINGS
  "설레다 (seollida) · to feel fluttery with excitement · berdebar-debar",
  "아쉽다 (aswipda) · to feel a tinge of regret · sayang sekali",
  "답답하다 (dapdapada) · to feel stifled / frustrated · sesak / gemas",
  "그립다 (geuripda) · to miss / long for · rindu",
  "민망하다 (minmanghada) · to feel awkward / embarrassed · canggung",
  "당황하다 (danghwanghada) · to be flustered · panik",
  "뿌듯하다 (ppudeutada) · to feel proud / fulfilled · bangga",
  "지겹다 (jigyeopda) · to be sick of / fed up · bosan banget",
  "귀찮다 (gwichanta) · to feel bothered / can't be asked · males",
  "아깝다 (akkapda) · what a waste · sayang (terbuang)",

  // EATING & DRINKING
  "배부르다 (baebureuda) · to be full · kenyang",
  "배고프다 (baegopeuda) · to be hungry · lapar",
  "목마르다 (mongmareuda) · to be thirsty · haus",
  "맵다 (maepda) · spicy · pedas",
  "짜다 (jjada) · salty · asin",
  "달다 (dalda) · sweet · manis",
  "시키다 (sikida) · to order (food) · pesan",
  "포장하다 (pojanghada) · to get it to-go · bungkus",
  "남기다 (namgida) · to leave (food) over · menyisakan",
  "한 잔 하다 (han jan hada) · to grab a drink · minum-minum",

  // GOING OUT & PLANS
  "약속 (yaksok) · appointment / plans · janji",
  "늦다 (neutda) · to be late · terlambat",
  "서두르다 (seodureuda) · to hurry · buru-buru",
  "데리러 가다 (derireo gada) · to go pick someone up · menjemput",
  "들르다 (deulleuda) · to drop by · mampir",
  "취소하다 (chwisohada) · to cancel · membatalkan",
  "미루다 (miruda) · to postpone · menunda",
  "기다리다 (gidarida) · to wait · menunggu",
  "만나다 (mannada) · to meet · bertemu",
  "놀러 가다 (nolleo gada) · to go hang out · pergi main",

  // CONVERSATION CONNECTORS
  "혹시 (hoksi) · by any chance · kalau-kalau",
  "그래도 (geuraedo) · even so / still · meskipun begitu",
  "오히려 (ohiryeo) · rather / on the contrary · justru",
  "역시 (yeoksi) · as expected · ternyata",
  "드디어 (deudieo) · finally · akhirnya",
  "어차피 (eochapi) · anyway / in any case · toh",
  "괜히 (gwaenhi) · for no reason · sia-sia",
  "별로 (byeollo) · not really · tidak begitu",
  "아마 (ama) · probably · mungkin",
  "그냥 (geunyang) · just (without reason) · cuma",

  // DAILY ACTIONS
  "챙기다 (chaenggida) · to take care to bring / look after · mengurus",
  "참다 (chamda) · to hold back / endure · menahan",
  "쉬다 (swida) · to rest · istirahat",
  "자다 (jada) · to sleep · tidur",
  "일어나다 (ireonada) · to get up · bangun",
  "씻다 (ssitda) · to wash up · cuci / mandi",
  "치우다 (chiuda) · to clean up / clear away · membereskan",
  "정리하다 (jeongrihada) · to organize / tidy · merapikan",
  "잃어버리다 (ireobeorida) · to lose (something) · kehilangan",
  "찾다 (chatda) · to look for / find · mencari",

  // DESCRIBING PEOPLE
  "착하다 (chakada) · nice / kind-hearted · baik hati",
  "다정하다 (dajeonghada) · warm / affectionate · hangat",
  "솔직하다 (soljikhada) · candid / honest · jujur",
  "꼼꼼하다 (kkomkkomhada) · meticulous · teliti",
  "느긋하다 (neugeutada) · laid-back · santai",
  "까칠하다 (kkachilhada) · prickly / standoffish · jutek",
  "웃기다 (utgida) · funny · lucu",
  "똑똑하다 (ttokttokada) · smart · pintar",
  "예민하다 (yeminhada) · sensitive · sensitif",
  "성격 (seonggyeok) · personality · kepribadian",

  // DESCRIBING THINGS
  "괜찮다 (gwaenchanta) · it's okay / decent · lumayan",
  "심심하다 (simsimhada) · boring · membosankan",
  "재미있다 (jaemiitda) · fun / interesting · seru",
  "신기하다 (singihada) · fascinating / curious · menakjubkan",
  "복잡하다 (bokjapada) · complicated · rumit",
  "간단하다 (gandanhada) · simple · sederhana",
  "비슷하다 (biseutada) · similar · mirip",
  "다르다 (dareuda) · different · berbeda",
  "특별하다 (teukbyeolhada) · special · istimewa",
  "평범하다 (pyeongbeomhada) · ordinary · biasa saja",

  // MONEY & SHOPPING
  "비싸다 (bissada) · expensive · mahal",
  "싸다 (ssada) · cheap · murah",
  "할인 (harin) · discount · diskon",
  "계산하다 (gyesanhada) · to pay / calculate · membayar",
  "돈 (don) · money · uang",
  "현금 (hyeongeum) · cash · tunai",
  "카드 (kadeu) · card · kartu",
  "영수증 (yeongsujeung) · receipt · struk",
  "사다 (sada) · to buy · membeli",
  "팔다 (palda) · to sell · menjual",

  // RELATIONSHIPS & SOCIAL
  "사귀다 (sagwida) · to date / get to know · pacaran",
  "헤어지다 (heeojida) · to break up · putus",
  "싸우다 (ssauda) · to fight / argue · bertengkar",
  "화해하다 (hwahaehada) · to make up / reconcile · berdamai",
  "오해 (ohae) · misunderstanding · salah paham",
  "부탁하다 (butakada) · to ask a favor · meminta tolong",
  "도와주다 (dowajuda) · to help · membantu",
  "고민 (gomin) · worry / dilemma · keresahan",
  "비밀 (bimil) · secret · rahasia",
  "소개하다 (sogaehada) · to introduce · memperkenalkan",


    // PARENTING — DAILY CARE
  "기저귀 (gijeogwi) · diaper · popok",
  "젖병 (jeotbyeong) · baby bottle · botol susu",
  "분유 (bunyu) · formula milk · susu formula",
  "이유식 (iyusik) · baby food · MPASI",
  "낮잠 (natjam) · nap · tidur siang",
  "재우다 (jaeuda) · to put to sleep · menidurkan",
  "달래다 (dallaeda) · to soothe / comfort · menenangkan",
  "안아주다 (anajuda) · to hold / hug · memeluk",
  "업다 (eopda) · to carry on the back · menggendong",
  "먹이다 (meogida) · to feed · menyuapi",
  "씻기다 (ssitgida) · to wash (a child) · memandikan",
  "갈아입히다 (garaipida) · to change clothes (on a child) · menggantikan baju",
  "재롱 (jaerong) · cute antics · tingkah lucu",
  "떼쓰다 (ttesseuda) · to throw a tantrum · merengek",
  "보채다 (bochaeda) · to fuss / be cranky · rewel",

  // PARENTING — GROWTH & MILESTONES
  "기다 (gida) · to crawl · merangkak",
  "걷다 (geotda) · to walk · berjalan",
  "옹알이 (ongari) · baby babbling · ocehan bayi",
  "말문이 트이다 (malmuni teuida) · to start talking · mulai bicara",
  "이가 나다 (iga nada) · teeth coming in · tumbuh gigi",
  "키가 크다 (kiga keuda) · to grow tall · bertambah tinggi",
  "성장 (seongjang) · growth · pertumbuhan",
  "발달 (baldal) · development · perkembangan",
  "버릇 (beoreut) · habit · kebiasaan",
  "예방접종 (yebangjeopjong) · vaccination · imunisasi",
  "소아과 (soagwa) · pediatrics · dokter anak",
  "열나다 (yeolnada) · to have a fever · demam",
  "감기 걸리다 (gamgi geollida) · to catch a cold · kena flu",
  "토하다 (tohada) · to throw up · muntah",
  "기침하다 (gichimhada) · to cough · batuk",

  // PARENTING — EMOTIONS & DISCIPLINE
  "혼내다 (honnaeda) · to scold · memarahi",
  "칭찬하다 (chingchanhada) · to praise · memuji",
  "타이르다 (taireuda) · to gently reason with · menasihati",
  "버릇없다 (beoreutopda) · ill-mannered / spoiled · kurang ajar",
  "기특하다 (giteukada) · admirable (of a child) · membanggakan",
  "대견하다 (daegyeonhada) · to be proud of (someone you've raised) · bangga",
  "철들다 (cheoldeulda) · to become mature · jadi dewasa",
  "사춘기 (sachungi) · puberty / teen phase · masa puber",
  "고집 (gojip) · stubbornness · keras kepala",
  "응석 (eungseok) · clinginess / spoiled behavior · manja",

  // SOFTWARE DEV — CORE WORK
  "개발자 (gaebalja) · developer · pengembang",
  "개발하다 (gaebalhada) · to develop · mengembangkan",
  "코드 (kodeu) · code · kode",
  "코딩하다 (kodinghada) · to code · ngoding",
  "버그 (beogeu) · bug · bug",
  "고치다 (gochida) · to fix · memperbaiki",
  "오류 (oryu) · error · galat",
  "에러 (ereo) · error · error",
  "테스트 (teseuteu) · test · tes",
  "배포 (baepo) · deployment · deploy",
  "배포하다 (baepohada) · to deploy · men-deploy",
  "출시 (chulsi) · release / launch · rilis",
  "기능 (gineung) · feature · fitur",
  "버전 (beojeon) · version · versi",
  "업데이트 (eopdeiteu) · update · pembaruan",

  // SOFTWARE DEV — PROCESS & TOOLS
  "리뷰 (ribyu) · review · ulasan",
  "검토하다 (geomtohada) · to review / examine · memeriksa",
  "커밋 (keomit) · commit · commit",
  "병합하다 (byeonghapada) · to merge · menggabungkan",
  "충돌 (chungdol) · conflict · konflik",
  "되돌리다 (doedollida) · to revert · mengembalikan",
  "리팩토링 (ripaektoring) · refactoring · refactor",
  "디버깅 (dibeoging) · debugging · debug",
  "기획 (gihoek) · planning / spec · perencanaan",
  "요구사항 (yogusahang) · requirements · persyaratan",
  "일정 (iljeong) · schedule · jadwal",
  "마감 (magam) · deadline · tenggat",
  "회의 (hoeui) · meeting · rapat",
  "공유하다 (gongyuhada) · to share · membagikan",
  "문서화 (munseohwa) · documentation · dokumentasi",

  // SOFTWARE DEV — STATES & PROBLEMS
  "작동하다 (jakdonghada) · to work / function · berfungsi",
  "안 되다 (an doeda) · not working · tidak jalan",
  "느려지다 (neuryeojida) · to slow down · jadi lambat",
  "멈추다 (meomchuda) · to stop / halt · berhenti",
  "터지다 (teojida) · to crash / blow up · meledak",
  "막히다 (makida) · to be blocked / stuck · tersumbat",
  "해결하다 (haegyeolhada) · to resolve · menyelesaikan",
  "원인 (wonin) · cause · penyebab",
  "재현하다 (jaehyeonhada) · to reproduce · mereproduksi",
  "임시 (imsi) · temporary · sementara",
  "수정하다 (sujeonghada) · to fix / modify · memperbaiki",
  "확인하다 (hwaginhada) · to check / confirm · memeriksa",
  "적용하다 (jeogyonghada) · to apply · menerapkan",
  "보완하다 (bowanhada) · to supplement / patch up · melengkapi",
  "최적화 (choejeokhwa) · optimization · optimasi",

  // DATA ENGINEERING
  "데이터 (deiteo) · data · data",
  "처리하다 (cheorihada) · to process · memproses",
  "분석 (bunseok) · analysis · analisis",
  "수집하다 (sujipada) · to collect · mengumpulkan",
  "저장하다 (jeojanghada) · to store · menyimpan",
  "불러오다 (bulleooda) · to load / fetch · memuat",
  "정제하다 (jeongjehada) · to clean / refine (data) · membersihkan",
  "변환하다 (byeonhwanhada) · to transform · mengubah",
  "추출하다 (chuchurada) · to extract · mengekstrak",
  "쿼리 (kweori) · query · kueri",
  "조회하다 (johoehada) · to look up / query · melihat",
  "용량 (yongryang) · capacity / volume · kapasitas",
  "속도 (sokdo) · speed · kecepatan",
  "지연 (jiyeon) · latency / delay · keterlambatan",
  "실행하다 (silhaenghada) · to run / execute · menjalankan",

  // OFFICE & TEAM LIFE
  "팀 (tim) · team · tim",
  "동료 (dongryo) · coworker · rekan kerja",
  "상사 (sangsa) · boss / superior · atasan",
  "부하 (buha) · subordinate · bawahan",
  "신입 (sinip) · new hire · karyawan baru",
  "이직 (ijik) · changing jobs · pindah kerja",
  "퇴사 (toesa) · quitting · resign",
  "면접 (myeonjeop) · interview · wawancara",
  "재택근무 (jaetaekgeunmu) · remote work · kerja dari rumah",
  "출장 (chuljang) · business trip · perjalanan dinas",
  "휴가 (hyuga) · vacation / leave · cuti",
  "연차 (yeoncha) · annual leave · cuti tahunan",
  "월급 (wolgeup) · monthly salary · gaji bulanan",
  "보너스 (boneoseu) · bonus · bonus",
  "성과 (seonggwa) · performance / results · prestasi",

  // TIME MANAGEMENT & FOCUS
  "집중하다 (jipjunghada) · to focus · fokus",
  "방해하다 (banghaehada) · to disturb / interrupt · mengganggu",
  "분주하다 (bunjuhada) · to be hectic · sibuk",
  "여유 (yeoyu) · breathing room · ada waktu / santai",
  "촉박하다 (chokbakada) · pressed for time · mepet",
  "미루다 (miruda) · to put off · menunda",
  "끝내다 (kkeutnaeda) · to finish · menyelesaikan",
  "마치다 (machida) · to complete · merampungkan",
  "진행하다 (jinhaenghada) · to proceed · melanjutkan",
  "준비하다 (junbihada) · to prepare · menyiapkan",

  // HOME LIFE
  "청소하다 (cheongsohada) · to clean · membersihkan",
  "빨래 (ppallae) · laundry · cucian",
  "설거지 (seolgeoji) · dishwashing · cuci piring",
  "요리하다 (yorihada) · to cook · memasak",
  "장 보다 (jang boda) · to grocery shop · belanja",
  "치우다 (chiuda) · to clear away · membereskan",
  "정리하다 (jeongrihada) · to tidy / organize · merapikan",
  "쓰레기 (sseuregi) · trash · sampah",
  "버리다 (beorida) · to throw away · membuang",
  "고장나다 (gojangnada) · to break down · rusak",

  // BODY & HEALTH
  "피곤하다 (pigonhada) · tired · capek",
  "졸리다 (jollida) · sleepy · ngantuk",
  "아프다 (apeuda) · to hurt / be sick · sakit",
  "두통 (dutong) · headache · sakit kepala",
  "어깨 (eokkae) · shoulder · bahu",
  "허리 (heori) · lower back · pinggang",
  "눈이 침침하다 (nuni chimchimhada) · eyes feel blurry · mata buram",
  "뻐근하다 (ppeogeunhada) · stiff (muscles) · pegal",
  "쉬어야겠다 (swieoyagetda) · I need to rest · harus istirahat",
  "운동하다 (undonghada) · to exercise · olahraga",

  // WEATHER & SEASONS
  "덥다 (deopda) · hot · panas",
  "춥다 (chupda) · cold · dingin",
  "쌀쌀하다 (ssalssalhada) · chilly · dingin sedikit",
  "후덥지근하다 (hudeopjigeunhada) · muggy · gerah",
  "비 오다 (bi oda) · to rain · hujan",
  "눈 오다 (nun oda) · to snow · turun salju",
  "맑다 (makda) · clear / sunny · cerah",
  "흐리다 (heurida) · cloudy · mendung",
  "장마 (jangma) · rainy season · musim hujan",
  "황사 (hwangsa) · yellow dust · debu kuning",

  // TRANSPORT & GETTING AROUND
  "차 막히다 (cha makida) · traffic jam · macet",
  "지하철 (jihacheol) · subway · MRT / kereta bawah tanah",
  "버스 (beoseu) · bus · bus",
  "택시 (taeksi) · taxi · taksi",
  "타다 (tada) · to ride / board · naik",
  "내리다 (naerida) · to get off · turun",
  "갈아타다 (garatada) · to transfer · ganti kendaraan",
  "걸어가다 (georeogada) · to walk (somewhere) · berjalan kaki",
  "주차하다 (juchahada) · to park · parkir",
  "도착하다 (dochakada) · to arrive · tiba",

  // QUICK REACTIONS & SMALL TALK
  "진짜요 (jinjjayo) · really? · serius?",
  "대박 (daebak) · awesome / no way · keren / wow",
  "헐 (heol) · whoa / OMG · astaga",
  "어머 (eomeo) · oh my · ya ampun",
  "그치 (geuchi) · right? · iya kan",
  "맞다 (matda) · oh right! (just remembered) · iya betul",
  "어쩌지 (eojjeoji) · what should I do · gimana ya",
  "어쩔 수 없다 (eojjeol su eopda) · can't be helped · mau bagaimana lagi",
  "다행이다 (dahaengida) · what a relief · syukurlah",
  "큰일이다 (keunirida) · this is a big problem · gawat",

  // OPINIONS & THOUGHTS
  "생각하다 (saenggakada) · to think · berpikir",
  "느끼다 (neukkida) · to feel · merasa",
  "기억나다 (gieoknada) · to remember · teringat",
  "잊다 (itda) · to forget · lupa",
  "동의하다 (donguihada) · to agree · setuju",
  "반대하다 (bandaehada) · to disagree / oppose · menolak",
  "이해하다 (ihaehada) · to understand · mengerti",
  "설명하다 (seolmyeonghada) · to explain · menjelaskan",
  "물어보다 (mureoboda) · to ask · bertanya",
  "대답하다 (daedapada) · to answer · menjawab",

  // PHONE & MESSAGING
  "전화하다 (jeonhwahada) · to call · menelepon",
  "문자 (munja) · text message · pesan teks",
  "보내다 (bonaeda) · to send · mengirim",
  "답장 (dapjang) · reply · balasan",
  "읽씹 (ikssip) · leaving on read · di-read doang",
  "알림 (allim) · notification · notifikasi",
  "끄다 (kkeuda) · to turn off · mematikan",
  "켜다 (kyeoda) · to turn on · menyalakan",
  "충전하다 (chungjeonhada) · to charge · mengisi daya",
  "끊기다 (kkeunkgida) · to get cut off (call/connection) · terputus",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
